sudo: required

services:
  - docker

before_install:
  - docker build -t steck032/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true steck032/docker-react npm run test -- --coverage
