language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test -- --coverage
 
deploy:
  provider: "elasticbeanstalk"
  env: "docker-env"
  region: "ap-south-1"
  app: "docker-react"
  bucket_name: "elasticbeanstalk-ap-south-1-252771581359"
  bucket_path: "docker-react"
  on:
    branch: "master"
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure:"$AWS_SECRET_ACCESS_KEY"
