version: '3.3'
services:
  react_server:
    restart: 'no'
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
     - "3000:3000"
    stdin_open: true
  test_server:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    volumes:  
      - "./src:/app/src"
    command: ["npm","run","test"]
    stdin_open: true
